## NumPy Examples

In [2]:
import numpy as np

In [3]:
def native_python_example():
    total = 0
    for x in range(1, 1_000_000):
        total += x
        return total

In [4]:
%timeit native_python_example()

346 ns ± 7.67 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
def numpy_example():
    return np.arange(1, 1_000_000).sum()

In [6]:
%timeit numpy_example()

899 µs ± 24.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
# native python
x = list(range(1, 1000))
y = [n + 1 for n in x]

In [8]:
x = np.array(range(1, 1000))

In [9]:
type(x)

numpy.ndarray

# N dimensional arrary

In [10]:
x = np.arange(1, 1000)

In [11]:
mask = x > 950

In [12]:
mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [13]:
x[mask]

array([951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963,
       964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976,
       977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989,
       990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [14]:
mask.sum() 

49

In [15]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [17]:
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a[0]

1

In [19]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [21]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])